### PR TITLE
Adding the License Warrior

### PR DESCRIPTION
**Pull request by RichardLitt**
Adding this while explicitly not mentioning the lack of a license in this repo.

### CODE REVIEW

**Comment by gregorni** [comment]
I think this should also include the guy who suggests a *change* of licenses, out of personal preference, or so that he canuse it for his own usecase.

**Comment by Jackenmen** [comment]
Sure, suggesting a change of license when there already is one is a bad thing (I sure hate people who try to shove GPL down someone's throat, e.g. https://github.com/uutils/coreutils/issues/834). But I don't see how asking for adding a license (if you checked for issue dups) is. Usually, if people share their code publicly on GitHub, they actually did mean to open-source it and just forgot about adding a license, I don't see why someone asking about it, even suggesting a license or two (perhaps linking to https://choosealicense.com/) would be bad behavior. Lack of license means that nobody can legally use that code so it's a valid ask, at least if the author hasn't previously indicated that they intentionally left the repo without license as more or less "All rights reserved".

**Comment by gregorni** [comment]
> Sure, suggesting a change of license when there already is one is a bad thing (I sure hate people who try to shove GPL down someone's throat, e.g. [uutils/coreutils#834](https://github.com/uutils/coreutils/issues/834)). But I don't see how asking for adding a license (if you checked for issue dups) is. Usually, if people share their code publicly on GitHub, they actually did mean to open-source it and just forgot about adding a license, I don't see why someone asking about it, even suggesting a license or two (perhaps linking to https://choosealicense.com/) would be bad behavior. Lack of license means that nobody can legally use that code so it's a valid ask, at least if the author hasn't previously indicated that they intentionally left the repo without license as more or less "All rights reserved".

I agree. I think the name " License Warrior" is great, but maybe better fits the guy who suggests a *change* of licenses.

**Comment by RichardLitt** [comment]
I think it works for either. I was trying to highlight the person who comes in and talks about the license _and nothing else_, especially without using the software or showing any inclination to do so. I think the "can you change the license?!" is another good example of the warrior. 

Suggesting a change of license, updating the year, or noting the lack of a license aren't annoying in themselves - it's how you do it.

**Comment by Jackenmen** [comment]
> I was trying to highlight the person who comes in and talks about the license _and nothing else_, especially without using the software

You can't really legally use the software if it has no license :) IMO it's not unreasonable for one's first (and "only", at least until the license is added) issue to be about the license. I would say that the vast majority of such issues are made with good intentions under the fair assumption that the repo owner forgot to add it/didn't know they have to if they want others to be able to use it. I personally haven't seen examples where the issue author would be unpleasant in such cases though I'm not saying it couldn't happen, I just think it's probably rare.

Anyway, what I'm trying to say here is that it may make sense to consider changing the comment example to something talking about changing the license.

**Comment by RichardLitt** [comment]
> You can't really legally use the software if it has no license

That's a user problem, not an issue for the author. It's unreasonable to ask for work from anyone if you're not interested in using the work afterwards, or in helping out. The no-return License quester I would say is unreasonable, in general. Maybe I could make that clearer in my PR? 

> I personally haven't seen examples where the issue author would be unpleasant in such cases though I'm not saying it couldn't happen, I just think it's probably rare.

I have. 

They are mainly made with good intentions. I edited the text to note about changing the license.

**Comment by Jackenmen** [comment]
> It's unreasonable to ask for work from anyone if you're not interested in using the work afterwards

I guess that's fair but do people outright say they won't use your work or how is it that you know? :thinking: I think it can sometimes happen that the author ends up not using it even though you were interested in the project at first since sometimes it may just turn out that it's not suitable or whatever but I'm not sure why a reasonable ask is a problem in itself if you have the issue tracker turned on in the first place, it's just like a feature request, right? People can be rude in any interaction, I'm not sure why this specific instance is worth mentioning any more than the generic rudeness in any other feature request.

> or in helping out.

I dunno, if one can't use, modify, or distribute it before the author adds the license then I feel like it's too soon to know if you're interested in helping out. In the end, not everyone is able to or wants to contribute, but as long as we're respectful of each other (not exhibiting any of the behaviors in the README :upside_down_face:), it shouldn't really be an issue.

> I have.

That sucks. I guess I can see some people just coming across some random project, seeing a lack of license, and immediately sending an issue, I don't think it's a problem in itself if they're nice about it but some people are just rude and entitled so yeah, I'm sorry that happened to you.

**Comment by gregorni** [comment]
I'm thinking, maybe we can also split this into two parts, "The License Warrior", who tries to change the project's license, and " The Legalist", who tries to add a license to the project.

**Comment by boneskull** [comment]
Adding a license is good, actually. We like open source, right?  But it should be done via issue; not a drive-by PR. 

I'm not sure the truly problematic behavior here--dropping a new license in a PR without any discussion--is differentiated from the "low-effort" PR. 

It is also fair to question an existing license _depending on the context_; some people adopt weird stuff like CC0 just because they don't know any better. 

I'm not sure of the best way to do this, since it may draw attention to the project owner's ignorance. But if I _intended_ that anyone could use my code and also explicitly took steps to _prevent_ that, I hope someone would tell me. 

Anyway, there's a fair bit of nuance and grey area around this. It might make sense to keep the list to behaviors which are easily expressed and understood. There's plenty of time for new OSS contributors to get into the licensing weeds!

**Comment by RichardLitt** [comment]
I should've seen this thread coming. :D 

@bradfitz - let me know what you'd like.

**Comment by bradfitz** [comment]
I actually think that asking about a license when there is none is reasonable behavior and we shouldn't 'shame' it by including it here. There are plenty of other dumb "IANAL, but ..." behaviors we could include, though. People not understanding CLAs and the different types of them are common.

This repo itself has no license because I'm not used to putting licenses on words (doc, presentations, blog posts, etc). For this repo, how do people feel about [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/) ?

**Comment by RichardLitt** [comment]
Fair! To be honest, I opened this mainly as a joke, because I noticed there wasn't one, but I didn't want to open an issue on a repo that I wasn't going to use very much, asking you to do work. I've done that before, and seen it before, and it never felt right. But I like your appraisal that that act isn't worth shaming. 

CC BY-NC-SA sounds reasonable to me.

**Pull request closed without merging**
